name: Upload to prod S3

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_PROD }}
        aws-region: eu-west-2

    - name: Upload files to S3
      shell: bash
      env:
        BUCKET: ${{ vars.PROD_BUCKET }}
        DISTRIBUTION: ${{ vars.PROD_DISTRIBUTION }}
      run: |
        aws s3 cp ./site/ s3://$BUCKET/ --recursive --exclude "_draft/*"
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION --paths '/*'
