name: Upload to S3

on:
  push:
    branches: [ dev ]

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_DEV }}
        aws-region: eu-west-2

    - name: Upload files to S3
      shell: bash
      env:
        BUCKET: ${{ vars.DEV_BUCKET }}
      run: |
        aws sts get-caller-identity
        aws s3 cp ./site/ s3://$BUCKET/ --recursive
